language: node_js
node_js:
  - 14
dist: trusty
services:
  - mongodb
  - redis-server
branches:
  only:
    - master
script:
  - npm run build
deploy:
  provider: heroku
  api_key: 7e450c9d-dc92-44df-8bba-284ac8717832
